### ISSUE TITLE
Installation issue: No module named gluu_oxd

### ISSUE THREAD

**Issue by ppilisi** [GluuFederation/gluru#1]
Hi,

I have a problem to execute migrations. When I run command 'python manage.py makemigrations' then get error "ImportError: No module named gluu_oxd". I don`t find this module with "pip search gluu_oxd" I installed module oxdpython but I get the same error.

We have a dedicated VM, where we are installing gluru and connecting it with other dependencies (DB, Gluu server, ...) over network where each component runs in a dedicated VM.

We have made sure that we have installed the same version of dependecies as in the documentation (python 2.7.6, mysql 5.6, redis 2.1, pip 18.0)

best regards,
Patrik

**Comment by mzico** [comment]
@ppilisi : Please use our support portal ( https://support.gluu.org ) for troubleshooting issue. Github is for feature request and bug tracking. Thanks.
